import type { Metadata } from "next";
import Link from "next/link";
import { MarketingNav, MarketingFooter } from "@/components/marketing-nav";

export const metadata: Metadata = {
  title: "What is Answer Engine Optimization (AEO)?",
  description:
    "Answer Engine Optimization (AEO) is the practice of making brands discoverable and citable in AI answers from ChatGPT, Perplexity, Gemini, and similar systems. Learn how AEO differs from SEO and how agencies deliver it.",
  keywords: [
    "what is AEO",
    "Answer Engine Optimization",
    "AEO vs SEO",
    "Generative Engine Optimization",
    "GEO",
    "optimize for ChatGPT",
    "AI citation optimization",
  ],
};

const faqs = [
  {
    q: "What is Answer Engine Optimization (AEO)?",
    a: "AEO is the discipline of improving how often and how accurately a brand appears in answers generated by AI systems such as ChatGPT, Perplexity, Gemini, and Claude. It focuses on citability, entity clarity, structured evidence, and content that models can quote with confidence.",
  },
  {
    q: "How is AEO different from traditional SEO?",
    a: "SEO optimizes for ranked blue links in search engines. AEO optimizes for inclusion inside synthesized answers. Technical foundations overlap (crawlability, clear structure, authority), but AEO adds emphasis on question-shaped content, factual density, brand entity consistency, and signals AI systems use when choosing sources.",
  },
  {
    q: "What is GEO (Generative Engine Optimization)?",
    a: "GEO is a closely related term for optimizing presence in generative AI engines. In practice agencies often use AEO and GEO interchangeably. AEO Command uses AEO as the primary product language.",
  },
  {
    q: "Why do agencies need an AEO tool?",
    a: "Clients ask for AI visibility the same way they once asked for rankings. Agencies need multi-client scanning, a prioritized fix list, team assignment, and white-label reporting — not a one-off public score page. That is the workflow AEO Command is built for.",
  },
  {
    q: "What does AEO Command check on a website?",
    a: "Scans evaluate signals that influence answer readiness: titles and meta, heading structure, structured data, content depth, about/entity clarity, llms.txt and machine-readable hints, and other extractable page signals — then turn gaps into Action Center tasks.",
  },
];

const faqJsonLd = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: faqs.map((f) => ({
    "@type": "Question",
    name: f.q,
    acceptedAnswer: { "@type": "Answer", text: f.a },
  })),
};

const articleJsonLd = {
  "@context": "https://schema.org",
  "@type": "Article",
  headline: "What is Answer Engine Optimization (AEO)?",
  description: metadata.description,
  author: { "@type": "Organization", name: "Threezero Agency" },
  publisher: { "@type": "Organization", name: "Threezero Agency" },
};

export default function AeoGuidePage() {
  return (
    <div className="flex min-h-screen flex-col bg-white">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(articleJsonLd) }}
      />
      <MarketingNav />
      <main className="flex-1 mx-auto max-w-3xl px-4 py-16 prose prose-slate">
        <p className="text-sm font-medium text-primary not-prose">Guide</p>
        <h1 className="text-3xl font-bold tracking-tight not-prose">
          What is Answer Engine Optimization (AEO)?
        </h1>
        <p className="text-muted-foreground not-prose mt-3 leading-relaxed">
          Answer Engine Optimization is how brands earn a place inside AI-generated
          answers — not only on the classic search results page.
        </p>

        <h2 className="text-xl font-semibold mt-10 not-prose">The shift</h2>
        <p className="text-sm text-muted-foreground leading-relaxed not-prose mt-2">
          People still search Google, but they also ask ChatGPT, Perplexity, and
          other assistants to summarize options, recommend vendors, and explain
          categories. Those systems do not show ten blue links the same way.
          They synthesize an answer and sometimes cite sources. If your client is
          invisible in that synthesis, demand never reaches the website.
        </p>

        <h2 className="text-xl font-semibold mt-10 not-prose">AEO vs SEO</h2>
        <p className="text-sm text-muted-foreground leading-relaxed not-prose mt-2">
          SEO remains essential for crawlability, authority, and organic traffic.
          AEO builds on the same foundations and adds: clear entity definition,
          question-aligned content, structured facts models can reuse, and
          measurement of whether the brand appears in answer-style outputs.
          Agencies that only deliver keyword rankings miss the new interface.
        </p>

        <h2 className="text-xl font-semibold mt-10 not-prose">
          What good AEO work looks like
        </h2>
        <ul className="text-sm text-muted-foreground space-y-2 not-prose mt-2 list-disc pl-5">
          <li>Unambiguous brand and product entity pages</li>
          <li>Structured data and consistent NAP / about facts</li>
          <li>Content that answers real buyer questions with citable specificity</li>
          <li>Technical access for crawlers and AI user-agents</li>
          <li>Ongoing tracking of prompt-level visibility, not vanity scores alone</li>
        </ul>

        <h2 className="text-xl font-semibold mt-10 not-prose">
          How AEO Command helps agencies
        </h2>
        <p className="text-sm text-muted-foreground leading-relaxed not-prose mt-2">
          AEO Command turns AEO into a delivery system: scan a client site, open a
          prioritized Action Center, assign work, track visibility prompts, and
          send a white-label report. That is the difference between a free checker
          and a product agencies can bill against.
        </p>

        <h2 className="text-xl font-semibold mt-10 not-prose">FAQ</h2>
        <div className="not-prose space-y-6 mt-4">
          {faqs.map((f) => (
            <div key={f.q}>
              <h3 className="font-medium text-sm">{f.q}</h3>
              <p className="mt-1 text-sm text-muted-foreground leading-relaxed">
                {f.a}
              </p>
            </div>
          ))}
        </div>

        <div className="not-prose mt-12 rounded-xl border p-6 text-center">
          <p className="font-medium">Put AEO on every client retainer</p>
          <p className="text-sm text-muted-foreground mt-1">
            Start a free trial of AEO Command — built for multi-client agencies.
          </p>
          <Link
            href="/signup"
            className="inline-block mt-4 rounded-md bg-primary px-5 py-2.5 text-sm font-medium text-primary-foreground"
          >
            Start free trial
          </Link>
        </div>
      </main>
      <MarketingFooter />
    </div>
  );
}
