"use client";
import {useEffect,useState} from "react";
type Provider={provider:string;status:string;model:string|null;timeoutMs:number;concurrencyLimit:number;rateLimitPerMinute:number;monthlyBudgetCents:number|null;credential:string|null;lastTestAt:string|null;lastTestStatus:string|null;lastError:string|null;monthlyUsage:{requestCount:number;estimatedCostCents:number}};
export default function ProviderControlPage(){
 const [rows,setRows]=useState<Provider[]>([]);const [busy,setBusy]=useState("");const [error,setError]=useState("");
 async function load(){const r=await fetch("/api/admin/providers");if(r.ok)setRows((await r.json()).providers||[]);else setError("Super Admin access required");}
 useEffect(()=>{load();},[]);
 async function save(p:Provider,enabled:boolean){setBusy(p.provider);setError("");const credential=window.prompt(enabled?"Enter the provider credential. It will never be shown again.":"Optional: enter a replacement credential, or leave blank.");const r=await fetch("/api/admin/providers",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({provider:p.provider,enabled,credential:credential||undefined,model:p.model||undefined,timeoutMs:p.timeoutMs,concurrencyLimit:p.concurrencyLimit,rateLimitPerMinute:p.rateLimitPerMinute,monthlyBudgetCents:p.monthlyBudgetCents})});if(!r.ok)setError((await r.json()).error||"Update failed");await load();setBusy("");}
 async function test(provider:string){setBusy(provider);const r=await fetch("/api/admin/providers/"+provider+"/test",{method:"POST"});const d=await r.json();if(!r.ok)setError(d.message||d.error||"Test failed");await load();setBusy("");}
 return <main className="mx-auto max-w-6xl space-y-6 p-4 sm:p-6"><header><h1 className="text-2xl font-semibold">Provider Control Plane</h1><p className="text-sm text-muted-foreground">Credentials, enablement, limits, tests, and monthly usage. Secrets are never rendered.</p></header>{error&&<div role="alert" className="rounded-md border border-red-200 bg-red-50 p-3 text-sm">{error}</div>}<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{rows.map(p=><section key={p.provider} className="rounded-xl border bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div><h2 className="font-medium capitalize">{p.provider}</h2><p className="text-xs text-muted-foreground">{p.credential||"No credential configured"}</p></div><span className="text-xs">{p.status}</span></div><dl className="mt-4 grid grid-cols-2 gap-2 text-xs"><div><dt className="text-muted-foreground">Model</dt><dd>{p.model||"Default"}</dd></div><div><dt className="text-muted-foreground">Timeout</dt><dd>{p.timeoutMs}ms</dd></div><div><dt className="text-muted-foreground">Concurrency</dt><dd>{p.concurrencyLimit}</dd></div><div><dt className="text-muted-foreground">Rate/min</dt><dd>{p.rateLimitPerMinute}</dd></div><div><dt className="text-muted-foreground">Requests</dt><dd>{p.monthlyUsage.requestCount}</dd></div><div><dt className="text-muted-foreground">Est. cost</dt><dd>{"$"+(p.monthlyUsage.estimatedCostCents/100).toFixed(2)}</dd></div></dl><p className="mt-3 text-xs">{p.lastTestStatus ? "Last test: "+p.lastTestStatus : "Not tested"}</p><div className="mt-4 flex gap-2"><button disabled={busy===p.provider} onClick={()=>save(p,p.status!=="ENABLED")} className="rounded-md border px-3 py-2 text-xs">{p.status==="ENABLED"?"Disable":"Configure & enable"}</button>{p.status==="ENABLED"&&<button disabled={busy===p.provider} onClick={()=>test(p.provider)} className="rounded-md bg-primary px-3 py-2 text-xs text-primary-foreground">Test</button>}</div></section>)}</div></main>;
}