CREATE TYPE "ProviderStatus" AS ENUM ('ENABLED','DISABLED');
CREATE TABLE "ProviderConfig" ("id" TEXT NOT NULL,"provider" TEXT NOT NULL,"status" "ProviderStatus" NOT NULL DEFAULT 'DISABLED',"model" TEXT,"timeoutMs" INTEGER NOT NULL DEFAULT 30000,"concurrencyLimit" INTEGER NOT NULL DEFAULT 4,"rateLimitPerMinute" INTEGER NOT NULL DEFAULT 60,"monthlyBudgetCents" INTEGER,"encryptedCredential" TEXT,"credentialFingerprint" TEXT,"lastTestAt" TIMESTAMP(3),"lastTestStatus" TEXT,"lastError" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "ProviderConfig_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "ProviderConfig_provider_key" ON "ProviderConfig"("provider");
CREATE INDEX "ProviderConfig_status_idx" ON "ProviderConfig"("status");
CREATE INDEX "ProviderConfig_lastTestStatus_lastTestAt_idx" ON "ProviderConfig"("lastTestStatus","lastTestAt");
CREATE TABLE "ProviderCredentialRotation" ("id" TEXT NOT NULL,"providerId" TEXT NOT NULL,"fingerprint" TEXT NOT NULL,"rotatedById" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"retiredAt" TIMESTAMP(3),CONSTRAINT "ProviderCredentialRotation_pkey" PRIMARY KEY ("id"));
CREATE INDEX "ProviderCredentialRotation_providerId_createdAt_idx" ON "ProviderCredentialRotation"("providerId","createdAt");
CREATE INDEX "ProviderCredentialRotation_rotatedById_createdAt_idx" ON "ProviderCredentialRotation"("rotatedById","createdAt");
CREATE TABLE "ProviderUsageEvent" ("id" TEXT NOT NULL,"providerId" TEXT NOT NULL,"agencyId" TEXT,"clientId" TEXT,"feature" TEXT NOT NULL,"model" TEXT,"requestCount" INTEGER NOT NULL DEFAULT 1,"inputTokens" INTEGER NOT NULL DEFAULT 0,"outputTokens" INTEGER NOT NULL DEFAULT 0,"estimatedCostCents" INTEGER NOT NULL DEFAULT 0,"status" TEXT NOT NULL DEFAULT 'SUCCESS',"latencyMs" INTEGER,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "ProviderUsageEvent_pkey" PRIMARY KEY ("id"));
CREATE INDEX "ProviderUsageEvent_providerId_createdAt_idx" ON "ProviderUsageEvent"("providerId","createdAt");
CREATE INDEX "ProviderUsageEvent_agencyId_createdAt_idx" ON "ProviderUsageEvent"("agencyId","createdAt");
CREATE INDEX "ProviderUsageEvent_clientId_createdAt_idx" ON "ProviderUsageEvent"("clientId","createdAt");
CREATE INDEX "ProviderUsageEvent_feature_createdAt_idx" ON "ProviderUsageEvent"("feature","createdAt");
CREATE TABLE "EmailTemplate" ("id" TEXT NOT NULL,"slug" TEXT NOT NULL,"name" TEXT NOT NULL,"subject" TEXT NOT NULL,"html" TEXT NOT NULL,"text" TEXT,"isActive" BOOLEAN NOT NULL DEFAULT true,"updatedById" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "EmailTemplate_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "EmailTemplate_slug_key" ON "EmailTemplate"("slug");
CREATE INDEX "EmailTemplate_isActive_idx" ON "EmailTemplate"("isActive");
CREATE TABLE "EmailDelivery" ("id" TEXT NOT NULL,"templateId" TEXT,"provider" TEXT NOT NULL,"toAddress" TEXT NOT NULL,"fromAddress" TEXT,"subject" TEXT NOT NULL,"status" TEXT NOT NULL DEFAULT 'QUEUED',"providerId" TEXT,"error" TEXT,"sentAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "EmailDelivery_pkey" PRIMARY KEY ("id"));
CREATE INDEX "EmailDelivery_status_createdAt_idx" ON "EmailDelivery"("status","createdAt");
CREATE INDEX "EmailDelivery_toAddress_createdAt_idx" ON "EmailDelivery"("toAddress","createdAt");
CREATE INDEX "EmailDelivery_provider_createdAt_idx" ON "EmailDelivery"("provider","createdAt");
ALTER TABLE "ProviderCredentialRotation" ADD CONSTRAINT "ProviderCredentialRotation_providerId_fkey" FOREIGN KEY ("providerId") REFERENCES "ProviderConfig"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ProviderCredentialRotation" ADD CONSTRAINT "ProviderCredentialRotation_rotatedById_fkey" FOREIGN KEY ("rotatedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ProviderUsageEvent" ADD CONSTRAINT "ProviderUsageEvent_providerId_fkey" FOREIGN KEY ("providerId") REFERENCES "ProviderConfig"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ProviderUsageEvent" ADD CONSTRAINT "ProviderUsageEvent_agencyId_fkey" FOREIGN KEY ("agencyId") REFERENCES "Agency"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ProviderUsageEvent" ADD CONSTRAINT "ProviderUsageEvent_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "EmailTemplate" ADD CONSTRAINT "EmailTemplate_updatedById_fkey" FOREIGN KEY ("updatedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "EmailDelivery" ADD CONSTRAINT "EmailDelivery_templateId_fkey" FOREIGN KEY ("templateId") REFERENCES "EmailTemplate"("id") ON DELETE SET NULL ON UPDATE CASCADE;